-- Таблица: типы товаров (например, Овощ, Фрукт, Напиток и т.д.)
CREATE TABLE table_product_types
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (name <> '')
);

-- Таблица: поставщики
CREATE TABLE table_suppliers
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (name <> '')
);

-- Таблица: товары
CREATE TABLE table_products
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT           NOT NULL CHECK (name <> ''),
    product_type_id INT            NOT NULL REFERENCES table_product_types (id) ON DELETE SET NULL,
    supplier_id     INT            NOT NULL REFERENCES table_suppliers (id) ON DELETE SET NULL,
    cost_price      DECIMAL(10, 2) NOT NULL CHECK (cost_price >= 0)

);

-- Таблица: поставки (приход товара)
CREATE TABLE table_deliveries
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id   INT                      NOT NULL REFERENCES table_suppliers (id) ON DELETE CASCADE,
    delivery_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Таблица: состав поставки (товары и их количество в поставке)
CREATE TABLE table_delivery_items
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id INT NOT NULL REFERENCES table_deliveries (id) ON DELETE CASCADE,
    product_id  INT NOT NULL REFERENCES table_products (id) ON DELETE CASCADE,
    quantity    INT NOT NULL CHECK (quantity > 0)
);

CREATE VIEW view_products AS
SELECT table_products.id, table_products.name, table_product_types.name AS product_type_name, table_suppliers.name AS supplier_name, cost_price
FROM table_products
         JOIN table_product_types ON table_products.product_type_id = table_product_types.id
JOIN table_suppliers ON table_products.supplier_id = table_suppliers.id;


-- Пример заполнения данными
-- Типы товаров
INSERT INTO table_product_types (name)
VALUES ('Fruit'),
       ('Vegetable'),
       ('Juice'),
       ('Dried Fruit');

-- Поставщики
INSERT INTO table_suppliers (name)
VALUES ('Fresh Farm'),
       ('Tropical Goods Inc.'),
       ('Local Market Co.');

-- Поставка
INSERT INTO table_deliveries (supplier_id, delivery_date)
VALUES ((SELECT id FROM table_suppliers WHERE name = 'Fresh Farm'), '2025-04-01 10:00:00'),
       ((SELECT id FROM table_suppliers WHERE name = 'Tropical Goods Inc.'), '2025-04-02 14:30:00');

-- Товары
INSERT INTO table_products (name, product_type_id, cost_price, supplier_id)
VALUES ('Apple', (SELECT id FROM table_product_types WHERE name = 'Fruit'), 30.00,
        (SELECT id FROM table_suppliers WHERE table_suppliers.name = 'Fresh Farm')),
       ('Banana', (SELECT id FROM table_product_types WHERE name = 'Fruit'), 45.50,
        (SELECT id FROM table_suppliers WHERE table_suppliers.name = 'Tropical Goods Inc.')),
       ('Carrot', (SELECT id FROM table_product_types WHERE name = 'Vegetable'), 20.00,
        (SELECT id FROM table_suppliers WHERE table_suppliers.name = 'Fresh Farm')),
       ('Orange Juice', (SELECT id FROM table_product_types WHERE name = 'Juice'), 80.00,
        (SELECT id FROM table_suppliers WHERE table_suppliers.name = 'Tropical Goods Inc.'));

-- Состав поставок
INSERT INTO table_delivery_items (delivery_id, product_id, quantity)
VALUES (1, (SELECT id FROM table_products WHERE name = 'Apple'), 100),
       (1, (SELECT id FROM table_products WHERE name = 'Carrot'), 200),
       (2, (SELECT id FROM table_products WHERE name = 'Banana'), 150),
       (2, (SELECT id FROM table_products WHERE name = 'Orange Juice'), 50);
