-- Таблица: типы товаров (например, Овощ, Фрукт, Напиток и т.д.)
CREATE TABLE table_product_types
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (name <> '')
);

-- Таблица: поставщики
CREATE TABLE table_suppliers
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (name <> '')
);

-- Таблица: товары
CREATE TABLE table_products
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT           NOT NULL CHECK (name <> ''),
    product_type_id INT            NOT NULL REFERENCES table_product_types (id) ON DELETE SET NULL,
    supplier_id     INT            NOT NULL REFERENCES table_suppliers (id) ON DELETE SET NULL,
    cost_price      DECIMAL(10, 2) NOT NULL CHECK (cost_price >= 0)

);

-- Таблица: поставки (приход товара)
CREATE TABLE table_deliveries
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id   INT                      NOT NULL REFERENCES table_suppliers (id) ON DELETE CASCADE,
    delivery_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Таблица: состав поставки (товары и их количество в поставке)
CREATE TABLE table_delivery_items
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id INT NOT NULL REFERENCES table_deliveries (id) ON DELETE CASCADE,
    product_id  INT NOT NULL REFERENCES table_products (id) ON DELETE CASCADE,
    quantity    INT NOT NULL CHECK (quantity > 0)
);

CREATE VIEW view_products AS
SELECT table_products.id, table_products.name, table_product_types.name AS product_type_name, table_suppliers.name AS supplier_name, cost_price
FROM table_products
         JOIN table_product_types ON table_products.product_type_id = table_product_types.id
JOIN table_suppliers ON table_products.supplier_id = table_suppliers.id;



TRUNCATE table_delivery_items, table_deliveries, table_products, table_suppliers, table_product_types CASCADE;

-- === ТИПЫ ТОВАРОВ (30) ===
INSERT INTO table_product_types (name)
VALUES
    ('Fruit'),
    ('Vegetable'),
    ('Juice'),
    ('Dried Fruit'),
    ('Dairy'),
    ('Bakery'),
    ('Meat'),
    ('Seafood'),
    ('Pasta'),
    ('Canned Food'),
    ('Frozen Food'),
    ('Snacks'),
    ('Beverages'),
    ('Coffee'),
    ('Tea'),
    ('Sweets'),
    ('Condiments'),
    ('Cleaning Supplies'),
    ('Personal Care'),
    ('Pet Food'),
    ('Cereals'),
    ('Nuts'),
    ('Herbs'),
    ('Spices'),
    ('Cheese'),
    ('Yogurt'),
    ('Eggs'),
    ('Butter'),
    ('Milk'),
    ('Honey');

-- === ПОСТАВЩИКИ (30) ===
INSERT INTO table_suppliers (name)
VALUES
    ('Fresh Farm'),
    ('Tropical Goods Inc.'),
    ('Local Market Co.'),
    ('Green Valley Distributors'),
    ('Organic Harvest Ltd'),
    ('Sunrise Provisions'),
    ('Alpine Dairy Group'),
    ('Ocean Fresh Seafood'),
    ('Golden Grain Mills'),
    ('Prime Meat Packers'),
    ('Sweet Tooth Confectionery'),
    ('Spice Route Traders'),
    ('Herb & Spice Co.'),
    ('Daily Bread Bakers'),
    ('Nuts & More'),
    ('Canned Classics'),
    ('Frozen Delights'),
    ('Beverage Masters'),
    ('Coffee Hub'),
    ('Tea Time Imports'),
    ('Dairy Direct'),
    ('Eggcellent Farms'),
    ('Butterfield Dairy'),
    ('Honeycomb Apiaries'),
    ('Pet Pantry'),
    ('Clean Home Supplies'),
    ('Beauty Essentials'),
    ('Farm to Table'),
    ('Quick Snacks Co.'),
    ('Milk Run Suppliers');

-- === ТОВАРЫ (30) ===
-- Используем подзапросы для связи с типами и поставщиками
INSERT INTO table_products (name, product_type_id, supplier_id, cost_price)
SELECT name,
       (SELECT id FROM table_product_types ORDER BY RANDOM() LIMIT 1),
       (SELECT id FROM table_suppliers ORDER BY RANDOM() LIMIT 1),
       ROUND((RANDOM() * 100 + 5)::NUMERIC, 2)
FROM (
         VALUES
             ('Apple'), ('Banana'), ('Carrot'), ('Orange Juice'), ('Whole Wheat Bread'),
             ('Cheddar Cheese'), ('Salmon Fillet'), ('Spaghetti'), ('Tuna Can'), ('Frozen Pizza'),
             ('Potato Chips'), ('Cola'), ('Espresso Beans'), ('Green Tea'), ('Chocolate Bar'),
             ('Ketchup'), ('Laundry Detergent'), ('Shampoo'), ('Dog Food'), ('Oatmeal'),
             ('Almonds'), ('Basil'), ('Cumin'), ('Greek Yogurt'), ('Free-Range Eggs'),
             ('Salted Butter'), ('Whole Milk'), ('Acacia Honey'), ('Cat Litter'), ('Energy Drink')
     ) AS t(name);

-- === ПОСТАВКИ (30) ===
-- Генерируем 30 поставок с рандомной датой за последние 60 дней
INSERT INTO table_deliveries (supplier_id, delivery_date)
SELECT
    (SELECT id FROM table_suppliers ORDER BY RANDOM() LIMIT 1),
    NOW() - (RANDOM() * 60 || ' days')::INTERVAL
FROM generate_series(1, 30);

-- === СОСТАВ ПОСТАВОК (30) ===
-- Каждая поставка — случайный товар и количество
INSERT INTO table_delivery_items (delivery_id, product_id, quantity)
SELECT
    (SELECT id FROM table_deliveries ORDER BY RANDOM() LIMIT 1),
    (SELECT id FROM table_products ORDER BY RANDOM() LIMIT 1),
    (RANDOM() * 50 + 1)::INT
FROM generate_series(1, 30);
